const INCORRECT_DATA_ERROR_CODE = 400;
const NOT_AUTH_ERROR_CODE = 401;
const NOT_OWNER_ENTITY_ERROR_CODE = 403;
const NOT_FOUND_CODE = 404;
const ALREADY_EXISTS_CODE = 409;
const DEFAULT_ERROR_CODE = 500;

const INCORRECT_DATA_ERROR_CODE_MESSAGE = 'Переданы некорректные данные';
const ALREADY_EXISTS_CODE_MESSAGE = 'Пользователь с такой почтой уже существует';

const {
  NODE_ENV = 'dev',
  JWT_SECRET,
  DB_ADDRESS = 'mongodb://127.0.0.1:27017/bitfilmsdb',
  PORT = 3000,
} = process.env;

module.exports = {
  INCORRECT_DATA_ERROR_CODE,
  NOT_AUTH_ERROR_CODE,
  NOT_OWNER_ENTITY_ERROR_CODE,
  NOT_FOUND_CODE,
  ALREADY_EXISTS_CODE,
  DEFAULT_ERROR_CODE,
  INCORRECT_DATA_ERROR_CODE_MESSAGE,
  ALREADY_EXISTS_CODE_MESSAGE,
  NODE_ENV,
  JWT_SECRET,
  DB_ADDRESS,
  PORT,
};
